#!/bin/bash
# скрипт загрузки и подготовки файлов портала https://www.svidbook.ru/

# пути и глобальные переменные
# определитель пути к папке с аудиокнигами - тут каждому своё
svid="https://www.svidbook.ru/books/"
afolder="/media/winda/Audiobooks"
temp="/tmp/$$.tmp"

# переменные для функции бэктранслита
path=
spath=

# уровень громкости, что-бы обойти ограничения кодека amr в слышимости хрипов на максималках
vl=0.9

# функция бектранслита без учёта регистра. Длинная, нудная, но очень глаза берегущая(транслит читать - садомазо)!
function get_cyr_path() {
	s="${spath}"; frasa=""

	for((i=0;$i<${#s};i++)); do
		variable=${s:$i:1}

		case $variable in
			a)
				res="а"
				;;
			b)
				res="б"
				;;
			c)
				if [ "${s:$(( i+1 )):1}" = "h" ]; then
					(( i++ ))
					res="ч"
				else
					res="ц"
				fi
				;;
			d)
				res="д"
				;;
			e)
				res="е"
				;;
			f)
				res="ф"
				;;
			g)
				res="г"
				;;
			h)
				res="х"
				;;
			i)
				a="${s:$(( i+1 )):1}"
				if [ "${a}" = "a" ]; then
					(( i++ ))
					res="я"
				else
					res="и"
				fi
				;;
			j)
				a="${s:$(( i+1 )):1}"
				if [ "${a}" = "a" ]; then
					(( i++ ))
					res="я"
				else
					res="й"
				fi
				;;
			k)
				res="к"
				;;
			l)
				res="л"
				;;
			m)
				res="м"
				;;
			n)
				res="н"
				;;
			o)
				res="о"
				;;
			p)
				res="п"
				;;
			q)
				res="ку"
				;;
			r)
				res="р"
				;;
			s)
				a="${s:$(( i+1 )):1}"
				b="${s:$(( i+2 )):1}"
				if [ "${a}" = "h" ]; then
					(( i++ ))
					res="ш"
				elif [[ "${a}" = "c" && "${b}" = "h" ]]; then
					(( i+=2 ))
					res="щ"
				else
					res="с"
				fi
				;;
			t)
				res="т"
				;;
			u)
				res="у"
				;;
			v)
				res="в"
				;;
			w)
				res="в"
				;;
			x)
				res="кс"
				;;
			y)
				if [ "${s:$(( i+1 )):1}" = "u" ]; then
					(( i++ ))
					res="ю"
				elif [ "${s:$(( i+1 )):1}" = "a" ]; then
					(( i++ ))
					res="я"
				else
					u=$((${#frasa}-1))
					a=${frasa:$u:1}
					# после согласных символ "y" обычно имеет нотацию "ы", а после гласных "й"
					case ${a} in
						"б"|"в"|"г"|"д"|"ж"|"з"|"к"|"л"|"м"|"н"|"п"|"р"|"с"|"т"|"ф"|"х"|"ц"|"ч"|"ш"|"щ")
							res="ы"
							;;
						*)
							res="й"
							;;
					esac
				fi
				;;
			z)
				if [ "${s:$(( i+1 )):1}" = "h" ]; then
					(( i++ ))
					res="ж"
				else
					res="з"
				fi
				;;
			-)
				res="_"
				;;
			*)
				res=${variable}
				;;
		esac
		frasa="${frasa}${res}"
	done
	path="${frasa}"
}

# Постраничная загрузка ссылок на все аудиокниги сайта
if [ ! -f ~/.svid_all ];then
	list=/tmp/$$.list
	for page in $(seq 1 1000); do
		if [ -f index.html ];then rm index.html; fi
		wget "${svid}page/${page}/"
		if [ ! -f index.html ]; then break; fi
		cat index.html|grep ${svid}|grep "<div class=\"func\">"|sed -r 's/^.*href="//'|sed -r 's/" title=.*//' > ${list}
		rm index.html
		for item in $(cat ${list}); do
			echo $item >> ~/.svid_all
		done
	done
	rm ${list}
fi

if [ ! -f ~/.svid_overhead ]; then touch ~/.svid_overhead; fi
if [ ! -f ~/.svid_last ]; then touch ~/.svid_last; fi

# Цикл загрузки аудиокниг
for item in $(cat ~/.svid_all);do
	tmp=$(grep "${item}" ~/.svid_overhead)
	if [ ! "${tmp}_" = "_" ]; then continue; fi
	cd "${afolder}"

# Загрузка страницы
	wget ${item} -O lst

# проверка подключения к тырьнету и выход если ничего не скачано
	fsize=$(wc -c lst|cut -f1 -d' ')
	if [ ${fsize} -eq 0 ]; then
		break
	fi

# Распарсивание html-ки
	cat lst|grep .mp3|sed 's/^<meta property=.*$//'|sed 's/data-mp3=\"/\n/g'|sed 's/\" data-title=\".*//g'|sed 's/.*li class.*$//'|sed '/^$/d' > ${temp}
	annot="$(grep "uk-margin-small-bottom\">Аннотация" lst -A 2|sed '1d; 3d;s/^[ \t]*//')"
	autor="$(grep "<h1>" lst | sed 's/-*<h1>//; s/<\/h1>.*//; s/\t//; s/ /_/g')"
	rm lst

	folder=$(basename ${item})
	folder="${folder:0:-5}"
	folder="$(echo ${folder}|sed -r 's/^[0-9]*-//')"
	spath="$(echo ${item}|sed 's/https.*\.ru\/books\///'|sed 's/\/.*//')"
	if [ "${autor}_" = "_" ]; then
		spath="${spath}/${folder}"
		get_cyr_path
		folder="${path}"
	else
		get_cyr_path
		folder="${path}/${autor}"
	fi

	if [ ! -d "${folder}" ];then
		mkdir -p "${folder}"
		cd "${folder}"
		echo "${folder}" > ~/.svid_last
		notify-send "${folder}"
	else
		notify-send "${folder} - уже был!"
	fi

	if [ ! "${annot}_" = "_" ];then
		echo "${annot}" > Аннотация
	else
		rm Аннотация
	fi

# Проверка была-ла начата перекодировка для прерванной обработки
	tmp=$(ls|grep .awb)
	if [ "${tmp}_" = "_" ];then
		# Загрузка mp3-шек
		for i in $(cat ${temp}); do
			if [ -f "${i}" ];then rm "${i}"; fi
			wget "${i}"
		done
	fi
	
# Перекодирование
	count=1
	for n in *.mp3; do
		name=$(echo ${n}|sed -r 's/^[0-9]*_//')
		spath="${name:0:-3}"
		get_cyr_path
		name="${path}awb"
		# переименование файла, если он существует
		if [ -f "${name}" ];then
			name="${path:0:-1}${count}.awb"
		fi
		if [ "${1}_" = "_" ];then
			nice -n 19 ffmpeg -threads 2 -i "${n}" -ac 1 -ab 18250 -ar 16000 -af volume=$vl -f amr -acodec libvo_amrwbenc "${name}"
			rm "${n}"
		else
			mv "${n}" "${name:0:-3}mp3"
		fi
	(( count++ ))
	done
	echo "${item}" >> ~/.svid_overhead
done

if [ -f ${temp} ];then rm ${temp}; fi
