#!/bin/bash

# определитель пути к папке с аудиокнигами
afolder="/media/winda/Audiobooks"

temp="/tmp/$$.tmp"

# Постраничная загрузка ссылок на все аудиокниги сайта
list=/tmp/$$.list
if [ ! -f ~/.svid_all ];then
for page in $(seq 1 1000); do
	if [ -f index.html ];then rm index.html; fi
	wget "https://www.svidbook.ru/books/page/${page}/"
	if [ ! -f index.html ]; then break; fi
	cat index.html|grep href=\"https:\/\/www.svidbook.ru\/books\/|grep "<div class=\"func\">"|sed -r 's/^.*href="//'|sed -r 's/" title=.*//' > ${list}
	rm index.html
	for item in $(cat ${list}); do
		echo $item >> ~/.svid_all
	done
done
fi
rm ${list}

if [ ! -f ~/.svid_overhead ]; then touch ~/.svid_overhead; fi
if [ ! -f ~/.svid_last ]; then touch ~/.svid_last; fi

# Цикл загрузки аудиокниг
for item in $(cat ~/.svid_all);do
	tmp=$(grep "${item}" ~/.svid_overhead)
	if [ ! "${tmp}_" = "_" ]; then continue; fi
	cd "${afolder}"
	folder=$(basename ${item})
	folder="${folder:0:-5}"
	folder="$(echo ${folder}|sed -r 's/^[0-9]*-//')"
	subfolder="$(echo ${item}|sed 's/https.*\.ru\/books\///'|sed 's/\/.*//')"
	folder="${subfolder}/${folder}"
	if [ ! -d "${folder}" ];then
		mkdir -p "${folder}"
		cd "${folder}"
		echo "${folder}" > ~/.svid_last
		notify-send "${folder}"
	else
		# если было прерывание работы на этапе обработки книги не стоит игнорировать её повторную обработку
#		tmp="$(grep "${folder}" ~/.svid_last)"
#		if [ "${tmp}_" = "_" ];then
			notify-send "${folder} - уже был!"
			echo "${item}" >> ~/.svid_overhead
			continue
#		fi
	fi

# Загрузка страницы
	wget ${item} -O lst

# проверка подключения к тырьнету и выход если ничего не скачано
	fsize=$(wc -c lst|cut -f1 -d' ')
	if [ ${fsize} -eq 0 ]; then
		rmdir "${folder}"
		break
	fi

# Распарсивание html-ки
	cat lst|grep .mp3|sed 's/^<meta property=.*$//'|sed 's/data-mp3=\"/\n/g'|sed 's/\" data-title=\".*//g'|sed 's/.*li class.*$//'|sed '/^$/d' > ${temp}
	rm lst

# Проверка была-ла начата перекодировка для прерванной обрабоки
	tmp=$(ls|grep .awb)
	if [ "${tmp}_" = "_" ];then
		# Загрузка mp3-шек
		for i in $(cat ${temp}); do
			wget "${i}"
		done
	fi

# Перекодирование
	for i in *.mp3; do
		name=$(echo ${i}|sed -r 's/^[0-9]*_//')
		name="${name:0:-3}awb"
#		if [ ! -f "${name}" ]; then
		nice -n 19 ffmpeg -i "${i}" -ac 1 -ab 18250 -ar 16000 -f amr -acodec libvo_amrwbenc "${name}"
		rm "${i}"
#		fi
	done
	echo "${item}" >> ~/.svid_overhead
done

if [ -f ${temp} ];then rm ${temp}; fi
